# Generated by Django 5.1.3 on 2024-12-06 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_product_tags'),
        ('ecommerce_app', '0003_contentpage_image'),
    ]

    operations = [
    ]
